# Generated by Django 2.1.3 on 2018-11-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('topic', models.CharField(max_length=1000)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
